# Generated by Django 4.1.3 on 2022-11-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Imagen de Consulta"
            ),
        ),
    ]
